/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AwardsRouteImport } from './routes/awards'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as CompaniesRouteImport } from './routes/companies'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CsrRouteImport } from './routes/csr'
import { Route as PeopleRouteImport } from './routes/people'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as SustainabilityRouteImport } from './routes/sustainability'
import { Route as TheGroupRouteImport } from './routes/the-group'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAwardsRouteImport } from './routes/admin.awards'
import { Route as AdminBlogRouteImport } from './routes/admin.blog'
import { Route as AdminCsrRouteImport } from './routes/admin.csr'
import { Route as AdminEnquiriesRouteImport } from './routes/admin.enquiries'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminProjectsRouteImport } from './routes/admin.projects'
import { Route as AdminReviewsRouteImport } from './routes/admin.reviews'
import { Route as AdminSustainabilityRouteImport } from './routes/admin.sustainability'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogPostIdRouteImport } from './routes/blog.$postId'
import { Route as CsrIndexRouteImport } from './routes/csr.index'
import { Route as CsrUpdateIdRouteImport } from './routes/csr.$updateId'
import { Route as ProjectsIndexRouteImport } from './routes/projects.index'
import { Route as ProjectsProjectIdRouteImport } from './routes/projects.$projectId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AwardsRoute = AwardsRouteImport.update({
  id: '/awards',
  path: '/awards',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const CompaniesRoute = CompaniesRouteImport.update({
  id: '/companies',
  path: '/companies',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CsrRoute = CsrRouteImport.update({
  id: '/csr',
  path: '/csr',
  getParentRoute: () => rootRouteImport,
} as any)
const PeopleRoute = PeopleRouteImport.update({
  id: '/people',
  path: '/people',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const SustainabilityRoute = SustainabilityRouteImport.update({
  id: '/sustainability',
  path: '/sustainability',
  getParentRoute: () => rootRouteImport,
} as any)
const TheGroupRoute = TheGroupRouteImport.update({
  id: '/the-group',
  path: '/the-group',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAwardsRoute = AdminAwardsRouteImport.update({
  id: '/admin/awards',
  path: '/admin/awards',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBlogRoute = AdminBlogRouteImport.update({
  id: '/admin/blog',
  path: '/admin/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCsrRoute = AdminCsrRouteImport.update({
  id: '/admin/csr',
  path: '/admin/csr',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEnquiriesRoute = AdminEnquiriesRouteImport.update({
  id: '/admin/enquiries',
  path: '/admin/enquiries',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProjectsRoute = AdminProjectsRouteImport.update({
  id: '/admin/projects',
  path: '/admin/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReviewsRoute = AdminReviewsRouteImport.update({
  id: '/admin/reviews',
  path: '/admin/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSustainabilityRoute = AdminSustainabilityRouteImport.update({
  id: '/admin/sustainability',
  path: '/admin/sustainability',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlogRoute,
} as any)
const BlogPostIdRoute = BlogPostIdRouteImport.update({
  id: '/$postId',
  path: '/$postId',
  getParentRoute: () => BlogRoute,
} as any)
const CsrIndexRoute = CsrIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CsrRoute,
} as any)
const CsrUpdateIdRoute = CsrUpdateIdRouteImport.update({
  id: '/$updateId',
  path: '/$updateId',
  getParentRoute: () => CsrRoute,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectsRoute,
} as any)
const ProjectsProjectIdRoute = ProjectsProjectIdRouteImport.update({
  id: '/$projectId',
  path: '/$projectId',
  getParentRoute: () => ProjectsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/awards': typeof AwardsRoute
  '/blog': typeof BlogRouteWithChildren
  '/companies': typeof CompaniesRoute
  '/contact': typeof ContactRoute
  '/csr': typeof CsrRouteWithChildren
  '/people': typeof PeopleRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/reviews': typeof ReviewsRoute
  '/sustainability': typeof SustainabilityRoute
  '/the-group': typeof TheGroupRoute
  '/admin/awards': typeof AdminAwardsRoute
  '/admin/blog': typeof AdminBlogRoute
  '/admin/csr': typeof AdminCsrRoute
  '/admin/enquiries': typeof AdminEnquiriesRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/projects': typeof AdminProjectsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/sustainability': typeof AdminSustainabilityRoute
  '/admin/users': typeof AdminUsersRoute
  '/blog/$postId': typeof BlogPostIdRoute
  '/csr/$updateId': typeof CsrUpdateIdRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/csr/': typeof CsrIndexRoute
  '/projects/': typeof ProjectsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/awards': typeof AwardsRoute
  '/companies': typeof CompaniesRoute
  '/contact': typeof ContactRoute
  '/people': typeof PeopleRoute
  '/reviews': typeof ReviewsRoute
  '/sustainability': typeof SustainabilityRoute
  '/the-group': typeof TheGroupRoute
  '/admin/awards': typeof AdminAwardsRoute
  '/admin/blog': typeof AdminBlogRoute
  '/admin/csr': typeof AdminCsrRoute
  '/admin/enquiries': typeof AdminEnquiriesRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/projects': typeof AdminProjectsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/sustainability': typeof AdminSustainabilityRoute
  '/admin/users': typeof AdminUsersRoute
  '/blog/$postId': typeof BlogPostIdRoute
  '/csr/$updateId': typeof CsrUpdateIdRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/admin': typeof AdminIndexRoute
  '/blog': typeof BlogIndexRoute
  '/csr': typeof CsrIndexRoute
  '/projects': typeof ProjectsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/awards': typeof AwardsRoute
  '/blog': typeof BlogRouteWithChildren
  '/companies': typeof CompaniesRoute
  '/contact': typeof ContactRoute
  '/csr': typeof CsrRouteWithChildren
  '/people': typeof PeopleRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/reviews': typeof ReviewsRoute
  '/sustainability': typeof SustainabilityRoute
  '/the-group': typeof TheGroupRoute
  '/admin/awards': typeof AdminAwardsRoute
  '/admin/blog': typeof AdminBlogRoute
  '/admin/csr': typeof AdminCsrRoute
  '/admin/enquiries': typeof AdminEnquiriesRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/projects': typeof AdminProjectsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/sustainability': typeof AdminSustainabilityRoute
  '/admin/users': typeof AdminUsersRoute
  '/blog/$postId': typeof BlogPostIdRoute
  '/csr/$updateId': typeof CsrUpdateIdRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/csr/': typeof CsrIndexRoute
  '/projects/': typeof ProjectsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/awards'
    | '/blog'
    | '/companies'
    | '/contact'
    | '/csr'
    | '/people'
    | '/projects'
    | '/reviews'
    | '/sustainability'
    | '/the-group'
    | '/admin/awards'
    | '/admin/blog'
    | '/admin/csr'
    | '/admin/enquiries'
    | '/admin/login'
    | '/admin/projects'
    | '/admin/reviews'
    | '/admin/sustainability'
    | '/admin/users'
    | '/blog/$postId'
    | '/csr/$updateId'
    | '/projects/$projectId'
    | '/admin/'
    | '/blog/'
    | '/csr/'
    | '/projects/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/awards'
    | '/companies'
    | '/contact'
    | '/people'
    | '/reviews'
    | '/sustainability'
    | '/the-group'
    | '/admin/awards'
    | '/admin/blog'
    | '/admin/csr'
    | '/admin/enquiries'
    | '/admin/login'
    | '/admin/projects'
    | '/admin/reviews'
    | '/admin/sustainability'
    | '/admin/users'
    | '/blog/$postId'
    | '/csr/$updateId'
    | '/projects/$projectId'
    | '/admin'
    | '/blog'
    | '/csr'
    | '/projects'
  id:
    | '__root__'
    | '/'
    | '/awards'
    | '/blog'
    | '/companies'
    | '/contact'
    | '/csr'
    | '/people'
    | '/projects'
    | '/reviews'
    | '/sustainability'
    | '/the-group'
    | '/admin/awards'
    | '/admin/blog'
    | '/admin/csr'
    | '/admin/enquiries'
    | '/admin/login'
    | '/admin/projects'
    | '/admin/reviews'
    | '/admin/sustainability'
    | '/admin/users'
    | '/blog/$postId'
    | '/csr/$updateId'
    | '/projects/$projectId'
    | '/admin/'
    | '/blog/'
    | '/csr/'
    | '/projects/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AwardsRoute: typeof AwardsRoute
  BlogRoute: typeof BlogRouteWithChildren
  CompaniesRoute: typeof CompaniesRoute
  ContactRoute: typeof ContactRoute
  CsrRoute: typeof CsrRouteWithChildren
  PeopleRoute: typeof PeopleRoute
  ProjectsRoute: typeof ProjectsRouteWithChildren
  ReviewsRoute: typeof ReviewsRoute
  SustainabilityRoute: typeof SustainabilityRoute
  TheGroupRoute: typeof TheGroupRoute
  AdminAwardsRoute: typeof AdminAwardsRoute
  AdminBlogRoute: typeof AdminBlogRoute
  AdminCsrRoute: typeof AdminCsrRoute
  AdminEnquiriesRoute: typeof AdminEnquiriesRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminProjectsRoute: typeof AdminProjectsRoute
  AdminReviewsRoute: typeof AdminReviewsRoute
  AdminSustainabilityRoute: typeof AdminSustainabilityRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/awards': {
      id: '/awards'
      path: '/awards'
      fullPath: '/awards'
      preLoaderRoute: typeof AwardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companies': {
      id: '/companies'
      path: '/companies'
      fullPath: '/companies'
      preLoaderRoute: typeof CompaniesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/csr': {
      id: '/csr'
      path: '/csr'
      fullPath: '/csr'
      preLoaderRoute: typeof CsrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/people': {
      id: '/people'
      path: '/people'
      fullPath: '/people'
      preLoaderRoute: typeof PeopleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sustainability': {
      id: '/sustainability'
      path: '/sustainability'
      fullPath: '/sustainability'
      preLoaderRoute: typeof SustainabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/the-group': {
      id: '/the-group'
      path: '/the-group'
      fullPath: '/the-group'
      preLoaderRoute: typeof TheGroupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/awards': {
      id: '/admin/awards'
      path: '/admin/awards'
      fullPath: '/admin/awards'
      preLoaderRoute: typeof AdminAwardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/blog': {
      id: '/admin/blog'
      path: '/admin/blog'
      fullPath: '/admin/blog'
      preLoaderRoute: typeof AdminBlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/csr': {
      id: '/admin/csr'
      path: '/admin/csr'
      fullPath: '/admin/csr'
      preLoaderRoute: typeof AdminCsrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/enquiries': {
      id: '/admin/enquiries'
      path: '/admin/enquiries'
      fullPath: '/admin/enquiries'
      preLoaderRoute: typeof AdminEnquiriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/projects': {
      id: '/admin/projects'
      path: '/admin/projects'
      fullPath: '/admin/projects'
      preLoaderRoute: typeof AdminProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/reviews': {
      id: '/admin/reviews'
      path: '/admin/reviews'
      fullPath: '/admin/reviews'
      preLoaderRoute: typeof AdminReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/sustainability': {
      id: '/admin/sustainability'
      path: '/admin/sustainability'
      fullPath: '/admin/sustainability'
      preLoaderRoute: typeof AdminSustainabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/$postId': {
      id: '/blog/$postId'
      path: '/$postId'
      fullPath: '/blog/$postId'
      preLoaderRoute: typeof BlogPostIdRouteImport
      parentRoute: typeof BlogRoute
    }
    '/csr/': {
      id: '/csr/'
      path: '/'
      fullPath: '/csr/'
      preLoaderRoute: typeof CsrIndexRouteImport
      parentRoute: typeof CsrRoute
    }
    '/csr/$updateId': {
      id: '/csr/$updateId'
      path: '/$updateId'
      fullPath: '/csr/$updateId'
      preLoaderRoute: typeof CsrUpdateIdRouteImport
      parentRoute: typeof CsrRoute
    }
    '/projects/': {
      id: '/projects/'
      path: '/'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/projects/$projectId': {
      id: '/projects/$projectId'
      path: '/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProjectsProjectIdRouteImport
      parentRoute: typeof ProjectsRoute
    }
  }
}

interface BlogRouteChildren {
  BlogPostIdRoute: typeof BlogPostIdRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogPostIdRoute: BlogPostIdRoute,
  BlogIndexRoute: BlogIndexRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface CsrRouteChildren {
  CsrUpdateIdRoute: typeof CsrUpdateIdRoute
  CsrIndexRoute: typeof CsrIndexRoute
}

const CsrRouteChildren: CsrRouteChildren = {
  CsrUpdateIdRoute: CsrUpdateIdRoute,
  CsrIndexRoute: CsrIndexRoute,
}

const CsrRouteWithChildren = CsrRoute._addFileChildren(CsrRouteChildren)

interface ProjectsRouteChildren {
  ProjectsProjectIdRoute: typeof ProjectsProjectIdRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
}

const ProjectsRouteChildren: ProjectsRouteChildren = {
  ProjectsProjectIdRoute: ProjectsProjectIdRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
}

const ProjectsRouteWithChildren = ProjectsRoute._addFileChildren(
  ProjectsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AwardsRoute: AwardsRoute,
  BlogRoute: BlogRouteWithChildren,
  CompaniesRoute: CompaniesRoute,
  ContactRoute: ContactRoute,
  CsrRoute: CsrRouteWithChildren,
  PeopleRoute: PeopleRoute,
  ProjectsRoute: ProjectsRouteWithChildren,
  ReviewsRoute: ReviewsRoute,
  SustainabilityRoute: SustainabilityRoute,
  TheGroupRoute: TheGroupRoute,
  AdminAwardsRoute: AdminAwardsRoute,
  AdminBlogRoute: AdminBlogRoute,
  AdminCsrRoute: AdminCsrRoute,
  AdminEnquiriesRoute: AdminEnquiriesRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminProjectsRoute: AdminProjectsRoute,
  AdminReviewsRoute: AdminReviewsRoute,
  AdminSustainabilityRoute: AdminSustainabilityRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
